server:
  port: 8084

spring:
  datasource:
    driver-class-name: @postgresql.driver@
    url: @postgresql.url@
    password: @postgresql.password@
    username: @postgresql.username@
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    show-sql: false