server:
  port: 8084

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/delivery
    password: root
    username: postgres
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    show-sql: false